// import React from 'react';
import Layer4 from '../Layer4.png';
import Layer5 from '../Layer5.png';
import Layer6 from '../Layer6.png';
import Layer8 from '../Layer8.png';
import Layer9 from '../Layer9.png';
import Layer10 from '../Layer10.jpg';
import RectangleGreen from '../RectangleGreen.png';
import RectangleBlue from '../RectangleDarkBlue.png';
import RectangleBlack from '../RectangleBlack.png';
import RectangleRed from '../RectangleRed.png';
import RectangleDarkBlue from '../RectangleDarkBlue.png';
const api={
    layerThree:[
        {number:1,img:Layer10,rectangleImg:RectangleGreen,text:'“When life gives you lemons ask it for sugar and water too. Otherwise your final product would be some acidic lemon juice!”',data:'10 Dectember 2018 |',author:'Priyavrat Gupta',contentHead:'INTERESTING FACTS ABOUT LEMONS',content:'Lemons are native to Asia.Lemons are a hybrid between a sour orange and a citron.Lemons are rich in vitamin C.Lemons trees can produce up to 600lbs of lemons every year.Lemon trees produce fruit all year round.Lemon zest, grated rinds, is often used in baking.Lemon tree leaves can be used to make tea.The high acidity of lemons make them good cleaning aids.California and Arizona produces most of the United States’ lemon crop.The most common types of lemons are the Meyer, Eureka, and Lisbon lemons.'},
        {number:2,img:Layer4,rectangleImg:RectangleBlue,text:'“Some people dream of success, while other people get up every morning and make it happen.“',data:'10 Dectember 2018 |',author:'Wayne Huizenga',contentHead:'President Barack Obama aims to change people`s lives.',content:'Obama once held the highest office in the land — but he doesn`t equate power with success.At the 2012 Democratic National Convention, First Lady Michelle Obama told the audience that her husband "started his career by turning down high-paying jobs and instead working in struggling neighborhoods where a steel plant had shut down.She went on:"For Barack, success isn\'t about how much money you make. It\'s about the difference you make in people\'s lives."'},
        {number:3,img:Layer6,rectangleImg:RectangleBlack,text:'“You can not build a great building on a weak foundation. You must have a solid foundation if you are going to have a strong superstructure.“',data:' 10 Dectember 2018 |',author:'Gordon B. Hinckley',contentHead:'Tallest Building In The World (Burj Khalifa, United Arab Emirates - 2,717 Feet)',content:'At 2,717 ft, Dubai\'s Burj Khalifa is the tallest building in the world. Primarily constructed from steel and concrete, the building was designed by the same architects who were responsible for other famous super-talls like the Willis Tower in Chicago and One World Trade Center in New York City. The construction of the building, which was completed in 2010, was part of an initiative by the government of the United Arab Emirates to shift the country’s economy from one that is solely oil-based to a more tourism and service based nation. The Burj Khalifa has 30,000 residences spread out over 19 residential towers, an artificial lake, nine hotels, and a shopping mall.'},
        {number:4,img:Layer8,rectangleImg:RectangleRed,text:'“Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.”',data:' 10 Dectember 2018 | ',author:'Mahatma Gandhi ',contentHead:'HOW DO WE FIND STARS IN THE SKY',content:'Some of the brighter stars appear to form groups in the sky, these we call constellations. Most constellations were named a very long time ago by the Greeks or Arabs. People thought they could see the shapes of animals or their gods and named the constellations after them. In most cases it is very hard to imagine how they saw the shape that the star pattern is supposed to represent but we still use the same names today. In the first 3 or 4 months of the year we see the winter constellations which include three very beautiful and interesting ones. These are called ORION the hunter, ANDROMEDA a Greek goddess and TAURUS the Bull.Constellations are not necessarily associations of stars, some groups of stars are not groups at all but are just in the same line of sight as seen from Earth. If you were able to view what we call a constellation from some other part of the sky (say looking at Orion from a planet orbiting a star in Taurus) it would look very different from the way we see it from Earth. Some stars appear bright in our sky because they are close to us, others may appear bright because they are giant bright stars. Some dim stars are actually very bright but are a very long way from us. We as humans always like to put things into groups so that we can sort them out in our minds, we do this with everything even with people so we do it with stars too. We are also quite good at remembering shapes and we often have good imaginations so just as we can see shapes of rabbits and elephants in the clouds it is not surprising therefore that we see shapes in the stars, these are the Constellations.To find your way around the sky, one other constellation can always be used to find your bearings, this is URSA MAJOR the Great Bear or Plough. Ursa Major is always visible in the northern sky, it is bright and easy to find. It is shaped like a saucepan with four stars forming the square shape of the pan and three more stars forming the handle. The two stars of the pan furthest from the handle are called the pointers because an imaginary line drawn through them points to the north star called Polaris. The pole star does not move in the sky and is always north of the point directly above us. By finding Polaris and turning around half a turn we will be facing south, and will then be able to use our star maps.'},
        {number:5,img:Layer9,rectangleImg:RectangleRed,text:'“Together we can face any challenges as deep as the ocean and as high as the sky.“',data:' 10 Dectember 2018 | ',author:'Sonia Gandhi',contentHead:'Unbelievable Facts About the Ocean',content:'Our oceans cover more than 70 per cent of the Earth’s surface.The majority of life on Earth is aquatic.Less than five per cent of the planet’s oceans have been explored.The world’s longest mountain chain is underwater.There are more historic artefacts under the sea than in all of the world’s museums.We still only know a fraction of the marine species in our oceans. Over 70 per cent of our planet’s oxygen is produced by the ocean. It’s possible to find rivers and lakes beneath the ocean.Around 50 per cent of the US lies beneath the ocean.The Pacific Ocean is the world’s largest ocean and contains around 25,000 islands.'},
        {number:6,img:Layer5,rectangleImg:RectangleDarkBlue,text:'“In life, usually, even if you live in a big city, you can count on your fingers on one hand how many real friends you have; that is human.“',data:' 10 Dectember 2018 | ',author:'Rodrigo Santoro',contentHead:'The most populated cities in the world',content:'1. Tokyo, Japan - Although its population is predicted to begin declining, Tokyo is still projected to hold the top spot as the most populated city on earth until 2030. Modern, stylish and full of culture, Tokyo is one of the most captivating cities to live but also the most tightly packed. And, in a city of approximately 38,140,000 people, you are sure to have a hard time pushing through the crowds to get to your destination.2. Delhi, India - With a population projected to reach 36 million by 2030, it may be an under-statement to say that Delhi is a very crowded city. Today, it is home to approximately 26,454,000 individuals. 3. Shanghai, China -As China’s most populated city, Shanghai is certainly not for those tired of the hustle-and-bustle of city life. With a population reaching 24,484,000 people, the city has become a financial center and home to the world’s busiest port.4. Mumbai, India - Attracting people from nearby cities because of its cosmopolitan charm and job opportunities, Mumbai now has a population of around 21,357,000 people. And with its total wealth reaching around US$280 billion, it certainly offers outstanding opportunities.5. São Paulo, Brazil - As the most populated city below the equator with an approximate population of 21,297,000, São Paulo houses an incredible array of institutions from finance to culture.  '}
    ],
    all:function () {
        return this.layerThree;
    },
    get: function(id) {
        const isImage = p => p.number === id;
        return this.layerThree.find(isImage);
    }
};
export default api;